
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stfrqfsereqoiiyehdfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZnJxZnNlcmVxb2lpeWVoZGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjUxODksImV4cCI6MjA1OTM0MTE4OX0.VWExau5P7syoRPiSX69LwRq7KdkBPHSaDWoMCU8OBCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
